services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: petshop-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petshop
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - pg_stat_statements.track=all
      - -c
      - track_io_timing=on
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: petshop-postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/petshop?sslmode=disable"
      PG_EXPORTER_EXTEND_QUERY_PATH: /etc/postgres_exporter/queries.yaml
    ports:
      - "9187:9187"
    volumes:
      - ./monitoring/queries.yaml:/etc/postgres_exporter/queries.yaml
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus
    container_name: petshop-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - postgres-exporter

  grafana:
    image: grafana/grafana
    container_name: petshop-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pgdata:
