services:
  router:
    image: postgres:16
    container_name: pg-router
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: router_db
    ports:
      - "5433:5432"

  shard1:
    image: postgres:16
    container_name: pg-shard1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shard1_db
    ports:
      - "5434:5432"

  shard2:
    image: postgres:16
    container_name: pg-shard2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shard2_db
    ports:
      - "5435:5432"

  master:
    image: postgres:16
    container_name: pg-partition-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: partition_db
    ports:
      - "5436:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10

  replica:
    image: postgres:16
    container_name: pg-partition-replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: partition_db
    ports:
      - "5437:5432"

volumes: {}
